In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import jieba
import nltk
from model import TrieNode

In [12]:
print ("/".join(jieba.cut("大乔为你点赞")))
jieba.add_word("大乔", freq = 10000, tag = None)
print ("/".join(jieba.cut("大乔为你点赞")))

大乔为/你/点赞
大乔/为/你/点赞


In [5]:
content = pd.read_csv("danmu_0.txt",header=None,sep= '\n',encoding = 'gbk')

In [6]:
content

0
0        完结撒花
1      看面包的眼神
2        全体起立
3      朋也你怎么了
4     大乔停止了思考
...       ...
1907     电车吃汗
1908     摩西摩西
1909    十六夜咲夜
1910       真实
1911      孔乙己

[1912 rows x 1 columns]

In [7]:
content.shape

(1912, 1)

In [10]:
cutted = []
for row in content.values:
    raw_words = (" ".join(jieba.cut(row[0])))
    cutted.append(raw_words)

In [11]:
cutted

['完结 撒花',
 '看 面包 的 眼神',
 '全体 起立',
 '朋也 你 怎么 了',
 '大乔 停止 了 思考',
 '兄弟 长椅 情',
 '黄金 精神',
 '不愧 是 乔鲁诺',
 '大乔 不 知道 应该 点赞 还是 沉默',
 '大乔 又 点 了 赞',
 '比如 压路机',
 '康一',
 '大乔为 你 点赞',
 'nice',
 '好 了 忘 了 这个 设定',
 '真就速 A 呗',
 '指 爽朗 的 偷 了 你 的 行李',
 '孔乙己 收到 一张 好人 卡',
 '乔纳森 也 很 痛心',
 '父词 子哮',
 '压路机 可以 吗',
 '呼叫 由 花子',
 '孔乙己 你长 荒木线 了',
 '民风 淳朴 意大利',
 '老汉 突然 出现',
 '大乔点 了 个 踩',
 '笑 死',
 '吼吼',
 '请 忘 了 这个 设定',
 '是 艺术',
 '再 放送',
 '传统 的 开局 先 揍 队友',
 '嘟噜 噜 噜 噜 噜 噜 噜 噜 噜 噜 噜',
 '完结 啦',
 '爽朗',
 '茸茸 天使',
 '又 被 吃掉 的 设定',
 '这是 前代 男二',
 '黄金 精神',
 '舞铲 阶级 vs 无铲 阶级',
 '舞铲 阶级 vs 无铲 阶级',
 '娘 不 嘞 斯',
 '男 的 女 的',
 '有产阶级 暴打 无产阶级',
 '大乔有 给 你 点 了 一个 赞',
 '太 上头 啦',
 '大乔 给 你 点赞',
 '雅 卡玛 系',
 '老老实实',
 '小野 们 的 奇妙 冒险',
 '乔家 代代 是 绅士',
 '护照 好歹 给 人家 吧',
 '老板 的 梦 开始 的 地方',
 '正道 得光',
 '正道 得光',
 '虽然 叫布姐 但是 布 加拉 提是 男 的 哦',
 '老板 梦 开始 的 地方',
 '收费 了',
 '呀 卡 吗 洗',
 '太 爷爷',
 '大乔 仰卧起坐 现场 吗 这 是',
 '人行道 不是 很 宽敞 吗',
 '孔乙己 没长 高',
 '不要 什么 东西 都 往 DNA 里刻 啊',
 '啊 乖乖 站 好',
 '仗助 点 了 个 赞',
 '是 男 是 女',
 '大乔 反复 撤销 他 的 赞',
 '波鲁 那雷夫',
 '有点 帅',
 'yesyesyes',
 '无铲 

In [2]:
seg_list = jieba.cut("我来到北京清华大学", cut_all=True)
print("Full Mode: " + "/ ".join(seg_list))  # 全模式
 
seg_list = jieba.cut("我来到北京清华大学", cut_all=False)
print("Default Mode: " + "/ ".join(seg_list))  # 精确模式
 
seg_list = jieba.cut("他来到了网易杭研大厦")  # 默认是精确模式
print(", ".join(seg_list))
 
seg_list = jieba.cut_for_search("小明硕士毕业于中国科学院计算所，后在日本京都大学深造")  # 搜索引擎模式
print(", ".join(seg_list))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\dell\AppData\Local\Temp\jieba.cache
Loading model cost 0.759 seconds.
Prefix dict has been built successfully.


Full Mode: 我/ 来到/ 北京/ 清华/ 清华大学/ 华大/ 大学
Default Mode: 我/ 来到/ 北京/ 清华大学
他, 来到, 了, 网易, 杭研, 大厦
小明, 硕士, 毕业, 于, 中国, 科学, 学院, 科学院, 中国科学院, 计算, 计算所, ，, 后, 在, 日本, 京都, 大学, 日本京都大学, 深造


UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 4: illegal multibyte sequence

In [10]:
import jieba
import re

with open('danmu_0.txt',encoding = 'gbk') as fin:
    raw_content = fin.read()
    raw_content = raw_content.strip()
# 请在下方作答 #
# step1：使用jieba分词
sent_list = []
sent_seg = jieba.cut(raw_content, cut_all=False)
sent_seg = ' '.join(sent_seg)
sent_list.append(sent_seg)

# step2：对分词结果进行统计

word_list = []
word_dict = {}

for each_sent in sent_list:
    [word_list.append(each_word)for each_word in each_sent.split(' ')]


for word in word_list:
    if len(word)<2:
        continue
    if word_dict.get(word):
        word_dict[word] += 1
    else:
        word_dict[word] = 1
        
# step3：对统计结果进行排序
topwords = list(word_dict.items())
topwords.sort(key = lambda x:x[1], reverse = True)
top_three = []
[top_three.append(topwords[num][0])for num in range(2)]
print (topwords)

[('大乔', 175), ('阶级', 37), ('杜王', 37), ('大木', 36), ('这个', 34), ('哈哈哈', 33), ('茸茸', 32), ('阿强', 32), ('点赞', 30), ('孔乙己', 29), ('黄金', 28), ('意大利', 28), ('电车', 27), ('还是', 26), ('精神', 25), ('布姐', 23), ('场面', 22), ('觉得', 22), ('绅士', 21), ('康一', 20), ('民风', 20), ('淳朴', 20), ('乔家', 20), ('十字军', 20), ('一个', 19), ('开始', 19), ('回来', 19), ('属于', 19), ('画风', 19), ('舞铲', 18), ('不见', 17), ('啊啊啊', 17), ('哈哈', 17), ('取消', 17), ('声音', 16), ('荣耀', 16), ('设定', 15), ('这么', 15), ('埃及', 15), ('意大利语', 15), ('怎么', 14), ('可以', 14), ('世界', 14), ('名画', 14), ('撤回', 14), ('前方', 14), ('永远', 14), ('平角', 13), ('祖传', 13), ('一次', 13), ('泪目', 13), ('乔鲁诺', 12), ('老汉', 12), ('老板', 12), ('几秒', 12), ('女人', 12), ('很赞', 12), ('星尘', 12), ('欧亚', 12), ('停止', 11), ('思考', 11), ('奇妙', 11), ('面板', 11), ('为什么', 11), ('nia', 11), ('飞机', 11), ('弹幕', 11), ('知道', 10), ('压路机', 10), ('荒木线', 10), ('仰卧起坐', 10), ('反复', 10), ('真的', 10), ('替身', 10), ('儿子', 10), ('好人', 9), ('承太郎', 9), ('欣慰', 9), ('星辰', 9), ('無用', 9), ('危危', 9), ('面包', 8), ('兄弟',

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
review_docs_arrays = []
with open("danmu_0.txt",'r') as fin:
    for line in fin.readlines():
        review_docs_arrays.append(line.strip())

# 请在下方作答 #
Vectorizer = CountVectorizer()
tf = Vectorizer.fit_transform(review_docs_arrays).toarray()

In [12]:
tf

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
review_docs_arrays = []
with open("danmu_0.txt",'r') as fin:
    for line in fin.readlines():
        review_docs_arrays.append(line.strip())

# 请在下方作答 #
Vectorizer = TfidfVectorizer(norm = 'l1')
tfidf_vec = Vectorizer.fit_transform(review_docs_arrays).toarray()
print (tfidf_vec)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
corpus = ['前方 噶能', '前方 高能','草' ,'什么鬼']
vec = TfidfVectorizer()
vec.fit_transform(corpus).toarray()

array([[0.        , 0.6191303 , 0.78528828, 0.        ],
       [0.        , 0.6191303 , 0.        , 0.78528828],
       [0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ]])

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
review_docs_arrays = []
with open("danmu_0.txt",'r') as fin:
    for line in fin.readlines():
        review_docs_arrays.append(line.strip())

# 请在下方作答 #
Vectorizer = CountVectorizer(ngram_range=(2,2))
bigram_vec = Vectorizer.fit_transform(corpus).toarray()

In [17]:
bigram_vec

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]], dtype=int64)

In [1]:
def shorten(s):
    ss= ''.join(reversed(s))
    k = -1
    j = 0
    array = [-1]
    plen = len(ss)
    zeros = 0
    nonze = 0
    while j < plen:
        if k == -1 or ss[j] == ss[k]:
            k += 1
            j += 1
            if k == 0:
                if j != zeros + 1:
                    loop = (int)(nonze/zeros) -1
                    return cut_string(s, plen) if loop<1 else cut_string(s, plen - zeros*loop)
                zeros += 1
            else:
                nonze += 1
            array.append(k)
        else:
            k = array[k]
    return cut_string(s, plen) if zeros==plen else (cut_string(s, zeros) if zeros>1 else cut_string(s, zeros+1)) 
def cut_string(s, lens):
    return s[0: lens]

In [3]:
print(shorten("23333333"))
print(shorten("wryyyyyyyy"))
print(shorten("ohhhhhhhhhhh"))
print(shorten("义勇啊啊啊啊啊啊"))
print(shorten("木大木大木大木大木大"))
print(shorten("你们有毒吧哈哈哈哈哈哈"))
print(shorten("得得得得得得得得得得得得得得得得得"))

233
wryy
ohh
义勇啊啊
木大
你们有毒吧哈哈
得得


In [42]:
"ananab"[0:2]

'an'

In [20]:
(int)(3/2)

1

In [4]:
text = [
    '完结撒花',
    '完结撒花',
    '完结撒花',
    '大乔停止了思考',
    '黄金精神',
    '黄金精神',
    '大乔又停止了思考'
]

In [8]:
cutted = []
for row in text:
    raw_words = (" ".join(jieba.cut(row)))
    cutted.append(raw_words)

In [9]:
cutted

['完结 撒花', '完结 撒花', '完结 撒花', '大乔 停止 了 思考', '黄金 精神', '黄金 精神', '大乔 又 停止 了 思考']

In [15]:
sent_list = []
for row in text:
    sent_seg = (" ".join(jieba.cut(row)))
    sent_list.append(sent_seg)

# step2：对分词结果进行统计

word_list = []
word_dict = {}

for each_sent in sent_list:
    [word_list.append(each_word)for each_word in each_sent.split(' ')]

for word in word_list:
    if len(word)<2:
        continue
    if word_dict.get(word):
        word_dict[word] += 1
    else:
        word_dict[word] = 1
        
# step3：对统计结果进行排序
topwords = list(word_dict.items())
topwords.sort(key = lambda x:x[1], reverse = True)
print (topwords)

['完结撒花', '完结撒花', '完结撒花', '大乔停止了思考', '黄金精神', '黄金精神', '大乔又停止了思考']
[('完结', 3), ('撒花', 3), ('大乔', 2), ('停止', 2), ('思考', 2), ('黄金', 2), ('精神', 2)]


In [ ]:
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
import jieba

# 分词及对文本向量化表示
list_text = [' '.join(word for word in jieba.cut(line) if word != ' ') for line in df_trainx.ix[:, 0]]
tfidf = TfidfVectorizer(max_df=0.95, stop_words=stopwords).fit(list_text)
array_trainx = tfidf.transform(list_text).toarray()

# PCA降维
pca = PCA()
pca.fit(array_trainx)
n_component = 0
while sum(pca.explained_variance_ratio_[0: n_component]) < 0.9:
    n_component += 1
pca = PCA(n_components=n_component)
array_trainx = pca.fit_transform(array_trainx)

# 训练模型
model = KMeans(n_clusters=2).fit(array_trainx)

# 输出预测结果
predict_value = model.labels_